
package view;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Venda;
import model.dao.CarroDAO;
import model.dao.ClienteDAO;
import model.dao.VendaDAO;


public class ViewVenda extends javax.swing.JFrame {

    /**
     * Creates new form ViewVenda
     */
    public ViewVenda() {
        initComponents();
        
        DefaultTableModel modelocliente = (DefaultTableModel) jtClienteVenda.getModel();
        jtClienteVenda.setRowSorter(new TableRowSorter(modelocliente));
        
        lerTabelaCliente();
        
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarroVenda.getModel();
        jtCarroVenda.setRowSorter(new TableRowSorter(modelocarro));

        lerTabelaCarro();
        
    }
    public void lerTabelaCliente() {
        
        DefaultTableModel modelocliente = (DefaultTableModel) jtClienteVenda.getModel();
        modelocliente.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();

        cdao.ler().forEach((c) -> {
            modelocliente.addRow(new Object[]{
                c.getId(),c.getNome(),c.getSobrenome(),c.getCpf()
            });
        });

    }
   
public void pesquisarNoBancoCliente(String l){
        
        DefaultTableModel modelocliente = (DefaultTableModel) jtClienteVenda.getModel();
        modelocliente.setNumRows(0);
        ClienteDAO cdao = new ClienteDAO();

        cdao.pesquisaCliente(l).forEach((c) -> {
            modelocliente.addRow(new Object[]{
                c.getId(),
                c.getNome(),
                c.getSobrenome(),
                c.getCpf()
                
            });
        });

    }

 public void lerTabelaCarro() {
        
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarroVenda.getModel();
        modelocarro.setNumRows(0);
        CarroDAO cdao = new CarroDAO();

        cdao.ler().forEach((c) -> {
            modelocarro.addRow(new Object[]{
                c.getId(),c.getModelo(),c.getAno(),c.getPlaca(),c.getValor()
            });
        });

    }
 
    public void pesquisarNoBancoCarro(String l){
        
        DefaultTableModel modelocarro = (DefaultTableModel) jtCarroVenda.getModel();
        modelocarro.setNumRows(0);
        CarroDAO cdao = new CarroDAO();

        cdao.pesquisaModelo(l).forEach((c) -> {
            modelocarro.addRow(new Object[]{
                c.getId(),
                c.getModelo(),
                c.getAno(),
                c.getPlaca(),
                c.getValor()
            });
        });

    }







    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtClienteVenda = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtCarroVenda = new javax.swing.JTable();
        btnBuscaClienteVend = new javax.swing.JButton();
        btnBuscaCarroVenda = new javax.swing.JButton();
        txtBuscaCarroVenda = new javax.swing.JTextField();
        txtBuscaClienteVenda = new javax.swing.JTextField();
        btnSalvarVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNomeVendedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        txtIdCarro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtClienteVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOME", "SOBRENOME", "CPF"
            }
        ));
        jtClienteVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtClienteVendaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtClienteVenda);

        jtCarroVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "MODELO", "ANO", "PLACA", "VALOR"
            }
        ));
        jtCarroVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCarroVendaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtCarroVenda);

        btnBuscaClienteVend.setText("Buscar Cliente");
        btnBuscaClienteVend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaClienteVendActionPerformed(evt);
            }
        });

        btnBuscaCarroVenda.setText("Buscar Carro");
        btnBuscaCarroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscaCarroVendaActionPerformed(evt);
            }
        });

        btnSalvarVenda.setText("Salvar");
        btnSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome do Vendedor");

        jLabel2.setText("ID CARRO");

        jLabel3.setText("ID CLIENTE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(271, 271, 271)
                                .addComponent(btnSalvarVenda))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(txtBuscaClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscaClienteVend)
                                .addGap(0, 8, Short.MAX_VALUE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(txtBuscaCarroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscaCarroVenda)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(txtBuscaClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaClienteVend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscaCarroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscaCarroVenda))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(btnSalvarVenda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscaClienteVendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaClienteVendActionPerformed

pesquisarNoBancoCliente(txtBuscaClienteVenda.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscaClienteVendActionPerformed

    private void btnBuscaCarroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscaCarroVendaActionPerformed
      pesquisarNoBancoCarro(txtBuscaCarroVenda.getText());
        
    }//GEN-LAST:event_btnBuscaCarroVendaActionPerformed

    private void jtCarroVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCarroVendaMouseClicked
        if (jtCarroVenda.getSelectedRow() != -1) {

            txtIdCarro.setText(jtCarroVenda.getValueAt(jtCarroVenda.getSelectedRow(), 0).toString());
            
            

        }
   
    }//GEN-LAST:event_jtCarroVendaMouseClicked

    private void jtClienteVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtClienteVendaMouseClicked
if (jtClienteVenda.getSelectedRow() != -1) {

            txtIdCliente.setText(jtClienteVenda.getValueAt(jtClienteVenda.getSelectedRow(), 0).toString());
            
            

        }


        // TODO add your handling code here:
    }//GEN-LAST:event_jtClienteVendaMouseClicked

    private void btnSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarVendaActionPerformed
        Venda v = new Venda();
        VendaDAO vdao = new VendaDAO();

        v.setVendedor(txtNomeVendedor.getText());
        v.setIdcliente(Integer.parseInt(txtIdCliente.getText()));
        v.setIdcarro(Integer.parseInt(txtIdCarro.getText()));
        
        vdao.create(v);

        
        txtIdCliente.setText("");
        txtIdCarro.setText("");
       
        lerTabelaCarro();
        lerTabelaCliente();



        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscaCarroVenda;
    private javax.swing.JButton btnBuscaClienteVend;
    private javax.swing.JButton btnSalvarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jtCarroVenda;
    private javax.swing.JTable jtClienteVenda;
    private javax.swing.JTextField txtBuscaCarroVenda;
    private javax.swing.JTextField txtBuscaClienteVenda;
    private javax.swing.JTextField txtIdCarro;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNomeVendedor;
    // End of variables declaration//GEN-END:variables
}
