/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Carro;
import model.dao.CarroDAO;



public class ViewCarro extends javax.swing.JFrame {

    
    public ViewCarro()  {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTCarros.getModel();
        jTCarros.setRowSorter(new TableRowSorter(modelo));

        lerTabelaCarro();

    }

    public void lerTabelaCarro() {
        
        DefaultTableModel modelo = (DefaultTableModel) jTCarros.getModel();
        modelo.setNumRows(0);
        CarroDAO cdao = new CarroDAO();

        cdao.ler().forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),c.getModelo(),c.getAno(),c.getPlaca(),c.getValor()
            });
        });

    }
    public void pesquisarNoBanco(String l){
        
        DefaultTableModel modelo = (DefaultTableModel) jTCarros.getModel();
        modelo.setNumRows(0);
        CarroDAO cdao = new CarroDAO();

        cdao.pesquisaModelo(l).forEach((c) -> {
            modelo.addRow(new Object[]{
                c.getId(),
                c.getModelo(),
                c.getAno(),
                c.getPlaca(),
                c.getValor()
            });
        });

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtModelo = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_cad = new javax.swing.JButton();
        btn_dlt = new javax.swing.JButton();
        btn_atua = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        txtValor = new javax.swing.JTextField();
        valor = new javax.swing.JLabel();
        btn_busca = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCarros = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modelo");

        jLabel2.setText("Ano");

        jLabel3.setText("Placa");

        btn_cad.setText("Cadastrar");
        btn_cad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadActionPerformed(evt);
            }
        });

        btn_dlt.setText("Excluir");
        btn_dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dltActionPerformed(evt);
            }
        });

        btn_atua.setText("Atualizar");
        btn_atua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atuaActionPerformed(evt);
            }
        });
        btn_atua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btn_atuaKeyReleased(evt);
            }
        });

        valor.setText("Valor");

        btn_busca.setText("Buscar");
        btn_busca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscaActionPerformed(evt);
            }
        });

        jTCarros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MODELO", "ANO", "PLACA", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTCarros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTCarrosMouseClicked(evt);
            }
        });
        jTCarros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTCarrosKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTCarros);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_busca)
                .addGap(114, 114, 114))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cad))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btn_dlt, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(valor)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(277, 277, 277))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_atua, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(valor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cad)
                    .addComponent(btn_dlt)
                    .addComponent(btn_atua))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_busca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTCarrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTCarrosKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jTCarrosKeyReleased

    private void jTCarrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTCarrosMouseClicked
        // TODO add your handling code here:

        if (jTCarros.getSelectedRow() != -1) {

            txtModelo.setText(jTCarros.getValueAt(jTCarros.getSelectedRow(), 1).toString());
            txtAno.setText(jTCarros.getValueAt(jTCarros.getSelectedRow(), 2).toString());
            txtPlaca.setText(jTCarros.getValueAt(jTCarros.getSelectedRow(), 3).toString());
            txtValor.setText(jTCarros.getValueAt(jTCarros.getSelectedRow(), 4).toString());

        }
    }//GEN-LAST:event_jTCarrosMouseClicked

    private void btn_buscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscaActionPerformed
        // TODO add your handling code here:

        pesquisarNoBanco(txtBusca.getText());
    }//GEN-LAST:event_btn_buscaActionPerformed

    private void btn_atuaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btn_atuaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_atuaKeyReleased

    private void btn_atuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atuaActionPerformed
        // TODO add your handling code here:

        if (jTCarros.getSelectedRow() != -1) {

            Carro c = new Carro();
            CarroDAO cdao = new CarroDAO();

            c.setModelo(txtModelo.getText());
            c.setAno(Integer.parseInt(txtAno.getText()));
            c.setPlaca(txtPlaca.getText());
            c.setValor(Float.parseFloat(txtValor.getText()));

            c.setId((int) jTCarros.getValueAt(jTCarros.getSelectedRow(), 0));
            cdao.update(c);

            txtModelo.setText("");
            txtAno.setText("");
            txtPlaca.setText("");
            txtValor.setText("");
            lerTabelaCarro();

        }
    }//GEN-LAST:event_btn_atuaActionPerformed

    private void btn_dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dltActionPerformed
        // TODO add your handling code here:

        if (jTCarros.getSelectedRow() != -1) {

            Carro c = new Carro();
            CarroDAO cdao = new CarroDAO();

            c.setId((int) jTCarros.getValueAt(jTCarros.getSelectedRow(), 0));

            cdao.delete(c);

            txtModelo.setText("");
            txtAno.setText("");
            txtPlaca.setText("");
            txtValor.setText("");
            lerTabelaCarro();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um carro para excluir.");
        }
    }//GEN-LAST:event_btn_dltActionPerformed

    private void btn_cadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadActionPerformed
        // TODO add your handling code here:

        Carro c = new Carro();
        CarroDAO cdao = new CarroDAO();

        c.setModelo(txtModelo.getText());
        c.setAno(Integer.parseInt(txtAno.getText()));
        c.setPlaca((txtPlaca.getText()));
        c.setValor(Float.parseFloat(txtValor.getText()));
        cdao.create(c);

        txtModelo.setText("");
        txtAno.setText("");
        txtPlaca.setText("");
        txtValor.setText("");

        lerTabelaCarro();
    }//GEN-LAST:event_btn_cadActionPerformed

        
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ViewCarro().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atua;
    private javax.swing.JButton btn_busca;
    private javax.swing.JButton btn_cad;
    private javax.swing.JButton btn_dlt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTCarros;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBusca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtValor;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
